server:
  port: 8080

spring:
  application:
    name: lifehub-gateway
  
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        
        - id: news_service
          uri: http://localhost:8080
          predicates:
            - Path=/news/**
          filters:
            - StripPrefix=0
        
        - id: goals_service
          uri: http://localhost:8080
          predicates:
            - Path=/goals/**
          filters:
            - StripPrefix=0
        
        - id: tasks_service
          uri: http://localhost:8080
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=0
        
        - id: health_check
          uri: http://localhost:8080
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=1
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.lifehub.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
