server:
  port: 8080

spring:
  application:
    name: lifehub-gateway
  
  cloud:
    gateway:
      routes:
        # Mock Auth Service
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        
        # Mock News Service
        - id: news_service
          uri: http://localhost:8080
          predicates:
            - Path=/news/**
          filters:
            - StripPrefix=0
        
        # Mock Goals Service
        - id: goals_service
          uri: http://localhost:8080
          predicates:
            - Path=/goals/**
          filters:
            - StripPrefix=0
        
        # Mock Tasks Service
        - id: tasks_service
          uri: http://localhost:8080
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=0
        
        - id: health_check
          uri: http://localhost:8080
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=1
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false
    binders:
      processor:
        enabled: false
      jvm:
        enabled: true
      system:
        enabled: true
      logback:
        enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.lifehub.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
